const form=document.getElementById('bookingForm');const priceEl=document.getElementById('price');const ctaPrice=document.getElementById('ctaPrice');const msg=document.getElementById('priceMessage');const error=document.getElementById('formError');const confirmation=document.getElementById('confirmation');const destination=document.getElementById('destination');const flightWrap=document.getElementById('flightWrap');const persons=document.getElementById('persons');document.getElementById('year').textContent=new Date().getFullYear();
for(let i=1;i<=8;i++){const o=document.createElement('option');o.value=i;o.textContent=`${i} ${i===1?'persoon':'personen'}`;persons.appendChild(o)}
const AIRPORT_WORDS=['airport','eindhoven airport','eindhoven luchthaven','schiphol','amsterdam airport'];
function isAirport(v){return AIRPORT_WORDS.some(x=>v.toLowerCase().includes(x))}
function updateFlight(){flightWrap.classList.toggle('hidden',!isAirport(destination.value))}destination.addEventListener('input',updateFlight);
function calc(){const d=destination.value.trim();const p=document.getElementById('pickup').value.trim();if(!d||!p){priceEl.textContent='€—';ctaPrice.textContent='Vaste prijs: €—';msg.textContent='Vul je ophaaladres en bestemming in voor de prijs.';return null}let price=37;if(isAirport(d))price=39;const t=document.getElementById('time').value;let night=false;if(t){const h=Number(t.split(':')[0]);night=h>=0&&h<6; if(night)price=Math.round(price*1.2*100)/100}priceEl.textContent=`€${price.toFixed(2).replace('.00','')}`;ctaPrice.textContent=`Vaste prijs: €${price.toFixed(2).replace('.00','')}`;msg.textContent='Vaste prijs — geen verrassingen achteraf.';return price}
['pickup','destination','date','time'].forEach(id=>document.getElementById(id).addEventListener('input',calc));
document.querySelectorAll('.payment').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.payment').forEach(x=>x.classList.remove('selected'));card.classList.add('selected')}));
function validPhone(v){return /^\s*(?:0\d{8,14}|\+\d{8,15})\s*$/.test(v.replace(/[()\-\s]/g,''))}
form.addEventListener('submit',e=>{e.preventDefault();error.hidden=true;confirmation.classList.add('hidden');const required=[['pickup','Vul je ophaaladres in.'],['destination','Vul je bestemming in.'],['date','Kies een datum.'],['time','Kies een ophaaltijd.'],['name','Vul je naam in.'],['phone','Vul je telefoonnummer in.']];for(const [id,text] of required){if(!document.getElementById(id).value.trim()){error.textContent=text;error.hidden=false;document.getElementById(id).focus();return}}const phone=document.getElementById('phone').value;if(!validPhone(phone)){error.textContent='Vul een geldig telefoonnummer in, bijvoorbeeld 06 12345678 of +31...';error.hidden=false;document.getElementById('phone').focus();return}const price=calc();if(!price){error.textContent='Controleer je ophaaladres en bestemming.';error.hidden=false;return}const data={name:document.getElementById('name').value.trim(),phone,pickup:document.getElementById('pickup').value.trim(),destination:document.getElementById('destination').value.trim(),date:document.getElementById('date').value,time:document.getElementById('time').value,persons:persons.value,luggage:document.getElementById('luggage').value,email:document.getElementById('email').value.trim(),flight:document.getElementById('flight').value.trim(),note:document.getElementById('note').value.trim(),payment:document.querySelector('input[name="payment"]:checked').value,price};localStorage.setItem('taxi_last_booking',JSON.stringify(data));confirmation.innerHTML=`<h2>✅ Ritaanvraag ontvangen</h2><p><b>${data.name}</b>, je aanvraag staat op <b>AANVRAAG</b> en is nog niet bevestigd.</p><p>🚕 ${data.pickup} → ${data.destination}<br>🗓️ ${data.date} om ${data.time}<br>👥 ${data.persons} personen • 🧳 ${data.luggage}<br>💳 ${data.payment}<br>💰 <b>€${price.toFixed(2).replace('.00','')}</b></p><p>De chauffeur moet de aanvraag eerst goedkeuren.</p>`;confirmation.classList.remove('hidden');confirmation.scrollIntoView({behavior:'smooth'});});
calc();updateFlight();